export const MAINTENANCE_LIBRARY = [
  {id:'hvac-filter', area:'Home', asset:'HVAC', title:'Replace HVAC air filter', intervalDays:60, costMin:10, costMax:30, difficulty:'Easy', safety:'low', tools:'Correct replacement filter', keywords:'air filter ac filter furnace filter dirty filter airflow dust allergies hvac', why:'A clogged filter can reduce airflow and make the system work harder.', steps:['Turn the HVAC system off.','Confirm the filter size and airflow arrow.','Remove the old filter and install the new one with the arrow pointing toward the blower.','Restart the system and write the date on the filter frame.']},
  {id:'hvac-service', area:'Home', asset:'HVAC', title:'HVAC seasonal service', intervalDays:180, costMin:100, costMax:250, difficulty:'Pro', safety:'medium', tools:'Licensed HVAC technician recommended', keywords:'ac tune up furnace tune up hvac service cooling heating inspection', why:'Seasonal service can catch worn parts, drainage problems and efficiency issues before peak weather.', steps:['Check that supply and return vents are clear.','Inspect the outdoor unit for debris.','Schedule professional service for refrigerant, electrical and combustion checks as applicable.']},
  {id:'smoke-test', area:'Home', asset:'Safety', title:'Test smoke and CO alarms', intervalDays:30, costMin:0, costMax:0, difficulty:'Easy', safety:'low', tools:'Step stool if needed', keywords:'smoke alarm carbon monoxide co detector chirp safety alarm', why:'Monthly testing confirms the alarm and power source can respond.', steps:['Tell everyone you are testing alarms.','Press and hold each test button until the alarm sounds.','Replace failed batteries or the whole alarm if it does not test correctly.']},
  {id:'smoke-battery', area:'Home', asset:'Safety', title:'Replace alarm batteries', intervalDays:180, costMin:8, costMax:30, difficulty:'Easy', safety:'low', tools:'Correct batteries', keywords:'smoke detector battery co alarm battery chirping', why:'Fresh batteries reduce nuisance chirps and help keep alarms ready.', steps:['Check the alarm label for the correct battery.','Replace the battery and close the compartment fully.','Press the test button after replacement.']},
  {id:'water-heater', area:'Home', asset:'Water heater', title:'Flush water heater sediment', intervalDays:365, costMin:0, costMax:150, difficulty:'Moderate', safety:'medium', tools:'Garden hose, bucket; follow manufacturer instructions', keywords:'water heater flush sediment hot water tank drain', why:'Sediment can reduce efficiency and may shorten tank life.', steps:['Read the manufacturer procedure first.','Turn off the energy source and allow water to cool as directed.','Use the drain valve and hose only if you are comfortable doing so.','Restore service exactly per the manufacturer instructions.']},
  {id:'dryer-vent', area:'Home', asset:'Laundry', title:'Clean dryer vent path', intervalDays:180, costMin:0, costMax:150, difficulty:'Moderate', safety:'medium', tools:'Vacuum and dryer vent brush', keywords:'dryer vent lint clothes dryer fire risk slow drying', why:'Lint buildup can restrict airflow, increase drying time and create a fire hazard.', steps:['Unplug the dryer or shut off power.','Clean the lint trap housing.','Inspect and clean the accessible vent path.','Confirm the exterior flap opens freely while the dryer runs.']},
  {id:'gutters', area:'Home', asset:'Exterior', title:'Clean gutters and downspouts', intervalDays:180, costMin:0, costMax:250, difficulty:'Moderate', safety:'medium', tools:'Gloves; ladder only if safe and appropriate', keywords:'gutter leaves downspout roof drainage rain overflow', why:'Clear drainage helps move roof water away from fascia and the foundation.', steps:['Work from the ground when possible.','Remove debris from reachable gutters safely.','Flush or verify downspouts discharge freely and away from the foundation.']},
  {id:'roof', area:'Home', asset:'Roof', title:'Visual roof inspection', intervalDays:365, costMin:0, costMax:250, difficulty:'Easy', safety:'medium', tools:'Binoculars or camera zoom', keywords:'roof shingle leak flashing hail storm inspection', why:'A ground-level inspection can reveal missing shingles, lifted flashing or storm damage early.', steps:['Inspect from the ground; do not climb onto a steep or unsafe roof.','Look for missing, curled or damaged shingles and loose flashing.','Check ceilings/attic areas for water staining after heavy rain.']},
  {id:'gfci', area:'Home', asset:'Electrical', title:'Test GFCI outlets', intervalDays:30, costMin:0, costMax:0, difficulty:'Easy', safety:'medium', tools:'None', keywords:'gfci outlet test reset bathroom kitchen outside electrical', why:'The built-in TEST button checks the protective trip mechanism.', steps:['Press TEST; connected power should shut off.','Press RESET to restore power.','If it will not trip or reset, stop using it and contact a qualified electrician.']},
  {id:'fridge-coils', area:'Home', asset:'Kitchen', title:'Clean refrigerator coils/vents', intervalDays:180, costMin:0, costMax:20, difficulty:'Easy', safety:'low', tools:'Vacuum with brush attachment', keywords:'refrigerator fridge coils dusty compressor hot fridge', why:'Dust on condenser coils or vents can reduce heat transfer and efficiency.', steps:['Unplug the refrigerator if the manual calls for it.','Find the condenser coils or ventilation area.','Vacuum dust gently without bending tubing or fins.']},
  {id:'pool-chemistry', area:'Pool', asset:'Water', title:'Test pool water chemistry', intervalDays:7, costMin:2, costMax:25, difficulty:'Easy', safety:'medium', tools:'Pool test kit or strips', keywords:'pool chlorine ph alkalinity cyanuric acid chemistry green cloudy water', why:'Regular testing helps prevent algae, scaling, corrosion and swimmer discomfort.', steps:['Test using your kit instructions.','Record chlorine/sanitizer and pH at minimum.','Adjust only one chemical at a time and follow product labels.','Never mix pool chemicals together.']},
  {id:'pool-baskets', area:'Pool', asset:'Circulation', title:'Empty skimmer and pump baskets', intervalDays:7, costMin:0, costMax:0, difficulty:'Easy', safety:'medium', tools:'Gloves', keywords:'pool skimmer basket pump basket leaves low suction vacuum circulation', why:'Full baskets restrict water flow and can make the pump work harder.', steps:['Turn the pump off before opening the pump strainer lid.','Empty skimmer baskets.','Empty the pump basket, inspect the lid O-ring and reseal the lid.','Restart and confirm the pump primes normally.']},
  {id:'pool-filter', area:'Pool', asset:'Filter', title:'Clean/backwash pool filter', intervalDays:30, costMin:0, costMax:80, difficulty:'Moderate', safety:'high', tools:'Follow filter and valve manufacturer instructions', keywords:'pool filter pressure high psi backwash cartridge de sand filter dirty filter', why:'A dirty filter can reduce circulation and increase system pressure.', steps:['Turn the pump OFF before moving any multiport or diverter valve.','Relieve pressure only according to the filter manufacturer instructions.','Clean, backwash or service the filter type you have.','Never open a pressurized filter tank.']},
  {id:'pool-valves', area:'Pool', asset:'Valves', title:'Inspect pool valves and labels', intervalDays:90, costMin:0, costMax:40, difficulty:'Easy', safety:'medium', tools:'Permanent labels or marker', keywords:'pool valve diverter skimmer main drain vacuum suction return plumbing handle', why:'Clear labels make troubleshooting and vacuum setup much easier and reduce accidental valve changes.', steps:['With the system in its normal safe condition, identify each line.','Label skimmer, main drain, vacuum and return lines where known.','Photograph the normal valve positions for reference.']},
  {id:'pool-light', area:'Pool', asset:'Electrical', title:'Inspect pool light operation', intervalDays:180, costMin:0, costMax:500, difficulty:'Pro', safety:'high', tools:'Licensed pool/electrical professional for faults', keywords:'pool light led niche breaker gfci underwater light not working', why:'Underwater electrical equipment deserves extra caution because water and electricity are involved.', steps:['Check operation from the normal switch/controller only.','If a GFCI trips, water is present in the fixture, or wiring is suspect, stop using the light.','Use a qualified pool/electrical professional for repair.']},
  {id:'vehicle-tires', area:'Vehicle', asset:'Tires', title:'Check tire pressure and tread', intervalDays:30, costMin:0, costMax:10, difficulty:'Easy', safety:'low', tools:'Tire gauge', keywords:'tire pressure psi tread low tire tpms car truck tahoe', why:'Correct pressure supports tire life, handling and fuel economy.', steps:['Check pressures when tires are cold.','Use the vehicle door-jamb pressure specification, not the tire sidewall maximum.','Inspect tread and sidewalls for uneven wear or damage.']},
  {id:'vehicle-oil', area:'Vehicle', asset:'Engine', title:'Check oil service status', intervalDays:120, costMin:50, costMax:150, difficulty:'Easy', safety:'low', tools:'Vehicle maintenance reminder/manual', keywords:'oil change engine oil service mileage maintenance car truck tahoe', why:'Oil service intervals vary by vehicle and use, so the vehicle reminder/manual should control the exact interval.', steps:['Check the oil-life monitor or maintenance schedule.','Record current mileage.','Schedule service when the manufacturer interval or oil-life system calls for it.']},
  {id:'vehicle-battery', area:'Vehicle', asset:'Battery', title:'Inspect vehicle battery', intervalDays:180, costMin:0, costMax:250, difficulty:'Easy', safety:'medium', tools:'Eye protection; battery tester optional', keywords:'car battery corrosion slow start no start terminals', why:'Corrosion, loose connections and a weak battery can cause unexpected no-start problems.', steps:['With the vehicle off, visually inspect for corrosion, swelling or loose connections.','Do not bridge battery terminals with tools.','Have the battery tested if starts are slow or the battery is aging.']},
  {id:'vehicle-wipers', area:'Vehicle', asset:'Visibility', title:'Inspect wiper blades and washer fluid', intervalDays:90, costMin:15, costMax:60, difficulty:'Easy', safety:'low', tools:'Correct replacement blades/fluid', keywords:'wiper blade streak windshield washer rain visibility', why:'Clear visibility matters most when weather turns bad.', steps:['Run the washers and wipers.','Replace blades that streak, chatter or leave unwiped areas.','Top off approved washer fluid.']},
  {id:'propane-smell', area:'Safety', asset:'Gas/Propane', title:'Gas or propane odor response', intervalDays:0, costMin:0, costMax:0, difficulty:'Emergency', safety:'critical', tools:'None', keywords:'propane smell gas leak rotten egg odor hissing gas emergency', why:'A suspected fuel-gas leak is not a DIY maintenance task.', steps:['Leave the area and avoid switches, flames, engines or anything that may create a spark.','From a safe location, contact the gas/propane supplier or emergency services as appropriate.','Do not return until the area has been declared safe.']}
];

export const PHOTO_LABELS = [
  'HVAC air filter','air conditioner outdoor condenser','smoke detector','carbon monoxide detector','water heater tank','dryer vent','roof shingles','rain gutter','GFCI electrical outlet','refrigerator condenser coils','swimming pool pump','swimming pool filter','pool diverter valve','pool skimmer basket','underwater pool light','car tire','car battery','engine oil dipstick'
];
